### ISSUE TITLE
运行Java代码时需要的系统调用过多

### ISSUE THREAD

**Issue by LinuZx** [iamwinter/LDUOnlineJudge#14]
C/C++的代码能正常评测，评测Java代码时报Runtime Error，具体消息如下：
[ERROR] A Not allowed system call: call id = 45, Please remove system function from your code!
然后我又把系统调用号45, 192, 85, 195, 197, 125, 243, 91, 258, 311, 174的都加上了可还是报错，请问有什么解决办法吗？
jdk版本号：jdk1.8.0_301

**Comment by iamwinter** [comment]
您好，
感谢您的反馈！

先给出一个可能的原因：
之前一直是基于ubuntu16.04测试，没有问题；近期修改了一些内容使之可以在ubuntu20.04上顺利运行，但忽略了对java的测试。请问您的ubuntu版本号是？ 

我会尽快测试并回复解决方法！谢谢！

**Comment by LinuZx** [comment]
我服务器的系统是CentOS，具体版本：CentOS Linux release 7.9.2009 (Core)

**Comment by iamwinter** [comment]
首先，在Ubuntu下测试一切正常。本项目目前还没有直接安装在centos上做过测试，直接在centos上运行judge程序可能存在一些错误，我会尽快使项目适配centos。

第二，在centos7（基于docker）下确认系统架构是`__x86_64`，说明系统调用的限制与Ubuntu一致即可。对java开放的系统调用（[这里](https://github.com/iamwinter/LDUOnlineJudge/blob/master/judge/cpp/judge.cpp#L51-L58)）最早参考自hustoj（[这里](https://github.com/zhblue/hustoj/blob/master/trunk/core/judge_client/okcalls64.h#L31-L37)），现在hustoj已经对这个数组进行了去重、优化。但hustoj中没有允许编号45。基于此，能否提供一下如下信息：
1. 是通过哪种安装方式安装的，以及启动判题进程时的用户是否具有root权限。
2. 报错的java完整代码。

建议：
1. 使用readme.md中提供的[基于docker安装](https://github.com/iamwinter/LDUOnlineJudge#wrench-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85)方式进行安装，然后升级一下。
2. 如果急需在centos上解决该问题，可以尝试采用上面提到的hustoj对java的系统调用编号数组，或者直接将该数组赋值为{0,1,2,...,255}（但不安全）。

再次感谢您的反馈。

**Comment by iamwinter** [comment]
另外提供一种debug方式，终端进入`judge/`，执行：
```shell
sudo bash startup.sh debug
```
然后在前台提交代码，在终端可以看到判题细节以及一些报错。

**Comment by LinuZx** [comment]
感谢作者大大的耐心解答，我是自己编写的web端，判题端是把您项目的judge文件夹移植到了服务器上，判题进程是以root身份启动的，目前我发现一个现象就是我提交空白的Main.java代码，判题端能正确编译但不会生成Main.class（因为是空白的代码），后续在running()函数中会执行指令/usr/bin/java java_xmx -Djava.security.manager Djava.security.policy=../../java.policy Main，按理说会报找不到Main.class的错误，但此时我这边就已经报系统调用不可用的错误，而且子进程执行/usr/bin/java命令时已经被父进程监视了，所以我认为可能是/usr/bin/java命令导致的系统调用不可用，另外我想请问下java.policy中对/usr/lib/jvm授予read权限，但是我没有/usr/lib/jvm目录，该如何修改。

**Comment by iamwinter** [comment]
关于报系统调用的问题，我重新看了代码，发现存在一个可疑的bug：即在编译时使用了javac的`-J-Xmx`(堆空间)`-J-Xms`(栈空间)来限制空间，然后又使用了C的`setrlimit`限制空间，形成了双重限制。我已经修改了代码（[这里](https://github.com/iamwinter/LDUOnlineJudge/blob/master/judge/cpp/judge.cpp#L311-L315)）去掉第二次限制。另外，`-J-Xmx`和`-J-Xms`参数指定的预分配空间，不宜过小，也不能太大引起服务器内存不足，已修改（[这里](https://github.com/iamwinter/LDUOnlineJudge/blob/master/judge/cpp/judge.cpp#L298)）。

`java.policy`的问题，由于时间久远，忘了当时是参考了哪里的策略，是不正确的。重新测试了一下，不需要赋予额外的权限。也就是说`java.policy`文件的内容应当修改为
```
grant{};
```
注意最后的分号。该文件必须有，否则会按jdk默认的策略（赋予所有权限）。参考：[使用Policy文件来设置Java的安全策略](https://blog.csdn.net/laiwenqiang/article/details/54376959)

**Comment by LinuZx** [comment]
我在hustoj找到了[解决方案](https://hub.fastgit.org/zhblue/hustoj/blob/master/wiki/CentOSx86_64.md)，在CentOS x86_64环境下，如果需要Java支持，请使用yum install java-1.6.0-openjdk java-1.6.0-openjdk-devel，建议不要使用官方的jdk，已证实不可用。在我我更换了jdk并允许125号系统调用后判题端能够正常评测Java代码了。另附上：[HUSTOJ出现RuntimeError,正确姿势。](https://zhuanlan.zhihu.com/p/24498599)
